реализация NotificationMessage
js-tasks-ru/js-20200928_aleksey786 pull request #5
Opened 2020-10-13 19:01 UTC by agmyzov

2020-10-13 19:10 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
NotificationMessage компонент
+ should be rendered correctly
+ should have ability to set duration
+ should be removed after time defined in duration property
+ should have ability to set message
+ should have ability to set 'success' type of message
+ should have ability to set 'error' type of message
+ should have ability to define target element for rendering
+ should have ability to be destroyed
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2020-10-14 21:30 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +  initEventListeners() {}
не оставляйте пустых методов

2020-10-14 21:30 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +  constructor(message = '',
good 👍

2020-10-14 21:32 UTC, dosandk requested changes
При добавлении нотификейшена на страницу, предыдущий нотификейшен должен быть удален. Не нашел реализации этой логики в Вашем решении

2020-10-16 16:44 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-10-16 17:03 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-10-18 11:32 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-10-18 15:48 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
>  class Tooltip {
В данном решение не хватает логики, которая позволяет тултипу перемещаться вслед за курсором мыши, пока курсор находится на элементом с соответствующим дата-атрибутом. Это нужно добавить

2020-10-18 15:49 UTC, dosandk commented on 06-events-practice/3-double-slider/index.js
> +  min; // number
не стоит объявлять данные значения как `class properties` без дефолтных значений, если в конструкторе все равно происходит присваивание `this.min = min;`

2020-10-18 15:50 UTC, dosandk commented on 06-events-practice/3-double-slider/index.js
> +        - this.innerElement.getBoundingClientRect()[style]
`this.innerElement.getBoundingClientRect()[style]` вот это значение явно хочет чтобы его вынесли в отдельную переменную. Согласны?

2020-10-18 15:51 UTC, dosandk requested changes
вцелом - хорошо. Поправьте пожалуйста решение Tooltip компонента

2020-10-19 06:21 UTC, agmyzov commented on 06-events-practice/2-tooltip/index.js
>  class Tooltip {
> В данном решение не хватает логики, которая позволяет тултипу перемещаться вслед за курсором мыши, пока курсор находится на элементом с соответствующим дата-атрибутом. Это нужно добавить

Добавлю. Помню, что при разборе домашки поведение было немного другое, но в постановке и тестах ничего не нашел, что упустил из виду. А тесты по результатам курса пополняются? Или это дополнительная проверка на внимательность?

2020-10-19 06:23 UTC, agmyzov commented on 06-events-practice/3-double-slider/index.js
> +  min; // number
> не стоит объявлять данные значения как `class properties` без дефолтных значений, если в конструкторе все равно происходит присваивание `this.min = min;`

Не отложилось что надо, а что нет указывать. Пересмотрю еще раз прошлую лекцию, где об этом говорилось.

2020-10-19 06:24 UTC, agmyzov commented on 06-events-practice/3-double-slider/index.js
> +        - this.innerElement.getBoundingClientRect()[style]
> `this.innerElement.getBoundingClientRect()[style]` вот это значение явно хочет чтобы его вынесли в отдельную переменную. Согласны?

Безусловно. Поправлю.

2020-10-19 17:09 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2020-10-20 18:06 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2020-10-20 19:08 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
>  class Tooltip {
Поглядывайте пожалуйста в задачник, там даже gif-ка есть которая показывает как должен вести себя тултип: https://learn.javascript.ru/taskbook/js-20200928/workspace/events-practice/tooltip

Уверяю Вас, в конце занятия мы смотрели демку в которой тултип приследовал курсор мыши, гляньте запись с временной метки 1:50:00

P.S. После каждой группы, я вношу какие-то правки в задания, описания и тесты, чтобы задачник и задания были максимально понятными и однозначными. Если нашли какие-то моменты которые можно улучшить - обязательно напишите, это будет большим плюсом в развитии курса

2020-10-20 19:10 UTC, dosandk commented on 07-async-code-fetch-api-part-1/1-column-chart/index.js
> +    return this.data.reduce(function (dataHTML, value) {
я советую всетаки отдавать предпочтение методу `map` при построении тимлейта компонента. Помните какие преимущества есть у `map` по сравнению со строковой конкатенацией?

2020-10-20 19:10 UTC, dosandk commented on 07-async-code-fetch-api-part-1/1-column-chart/index.js
> +    //TODO: обработку ошибок сделать
про обработку ошибок будем говорить на след занятии

2020-10-20 19:11 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +      document.addEventListener('pointermove', this.onPointerMove);
good 👍

2020-10-20 19:11 UTC, dosandk approved these changes

2020-10-20 19:11 UTC, jsru commented
PR не может быть принят, обратитесь, пожалуйста, к преподавателю.

2020-10-21 14:25 UTC, agmyzov commented on 07-async-code-fetch-api-part-1/1-column-chart/index.js
> +    return this.data.reduce(function (dataHTML, value) {
Да, переделаю. При строковой конкатенации каждый раз создается новый объект, так как строка неизменна.

2020-10-21 18:52 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2020-10-22 14:23 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2020-10-23 16:56 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2020-10-24 21:17 UTC, dosandk approved these changes

2020-10-24 21:17 UTC, jsru commented
PR не может быть принят, обратитесь, пожалуйста, к преподавателю.

2020-10-24 21:24 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
RangePicker компонент
- should be rendered correctly
- should initially show only input
- should be opened on click
- should be closed on second click
- should show selected dates 'dateFrom-dateTo' in input
- should highlight selected 'from' and 'to' dates in calendar
- should highlight selected dates range in calendar
- should clear highlighting of previous selection
- should keep selected dates range after reopening
- should show correct initial months in calendar
- should have ability to switch to the next couple of months
- should have ability to switch to the previous couple of months
- should have ability to select all dates in two visible months
- should have ability to select dates range bigger than two months
- should not change dates 'from' and 'to' inside input element if selected only one date
- should have ability to select minimal dates range equal two days
- should have ability to select minimal dates range equal one day
- should have ability select more than 1 year dates range
- should have ability to be removed
```
```diff
DoubleSlider компонент
+ should be rendered correctly
+ should have ability to set slider boundaries
+ should have ability to set selected range
+ should have ability to move left slider to start boundary
+ should have ability to move right slider to end boundary
+ should have ability to select all range
+ should have ability to select single value (when min and max range equal)
+ should have ability to set range value, for example: usd, eur, etc.
+ should produce event "range-select"
+ should have a new ranges in produced event
+ should have ability to be destroyed
```
```diff
SortableTable компонент - без обработчиков событий клика и динамической загрузки
+ should be rendered correctly
+ should not have default sorting
+ should sort "asc" correctly for "sortType" equal string
+ should sort "desc" correctly for "sortType" equal string
+ should sort "asc" correctly for "sortType" equal number
+ should sort "desc" correctly for "sortType" equal number
+ should have ability to be destroyed
```
```diff
SortableTable v2 компонент без динамической загрузки данных
+ should be rendered correctly
+ should have default sorting marked by arrow icon
+ should sort "desc" correctly for "sortType" equal string
+ should sort "desc" correctly for "sortType" equal number
+ should move arrow icon to the corresponding column after sorting
+ should have ability to be destroyed
```
```diff
SortableTable v3 с динамической загрузкой данных и "infinity scroll"
+ should be rendered correctly
+ should call "loadData" method
+ should render loaded data correctly
+ should sort data correctly
+ should have ability to be destroyed
```
```diff
NotificationMessage компонент
+ should be rendered correctly
+ should have ability to set duration
+ should be removed after time defined in duration property
+ should have ability to set message
+ should have ability to set 'success' type of message
+ should have ability to set 'error' type of message
+ should have ability to define target element for rendering
+ should have ability to be destroyed
```
```diff
ColumnChart компонент с динамической загрузкой данных
+ should be rendered correctly
+ should have ability to define label
+ should have ability to define link
+ should have property 'chartHeight'
+ should render data correctly
+ should have ability to be update by new values
+ should have loading indication if data wasn't passed 
+ should have ability to be destroyed
```
```diff
Tooltip компонент
+ should be rendered correctly
+ should be shown when moving over the element with data-tooltip attribute
+ should be hidden when moving out from the element with data-tooltip attribute
+ should have ability to be destroyed
```

2020-10-24 21:45 UTC, dosandk commented
@agmyzov поправьте пожалуйста тесты

2020-10-25 05:53 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-10-27 18:08 UTC, dosandk commented on 08-forms-fetch-api-part-2/2-range-picker/index.js
> +    switch (month) {
можно сделать вот так:
```
const months = new Array(12)
  .fill(1)
  .map((_, index) => {
    return new Date(new Date().setMonth(index))
      .toLocaleString('ru', { month: 'long'})
  });
```

2020-10-27 18:09 UTC, dosandk commented on 08-forms-fetch-api-part-2/2-range-picker/index.js
> +    return `<div class="rangepicker__day-of-week">
попробуйте переделать данную функцию:
```
const months = new Array(12)
  .fill(1)
  .map((_, index) => {
    return new Date(new Date().setMonth(index))
      .toLocaleString('ru', { month: 'long'})
  });
```
для получения списка дней недели

подробнее можно посмотреть вот тут https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString

2020-10-27 18:10 UTC, dosandk approved these changes

2020-10-27 18:12 UTC, merged